version: '3.8'

services:
  node-app:
    build: .
    container_name: my-node-app
    ports:
      - '8080:8080'  
    environment:
      PORT: 8080  
      DB_PORT: 3307 
      DB_HOST: mysql-db 
      DB_USER: root  
      DB_PASS: root
      MYSQL_DB: spotify

  mysql-db:
    image: mysql:latest
    container_name: my-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3307'
